//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string ChiTiet {
            get {
                return ResourceManager.GetString("ChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết yêu cầu.
        /// </summary>
        internal static string ChiTietYeuCau {
            get {
                return ResourceManager.GetString("ChiTietYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        internal static string CongTy {
            get {
                return ResourceManager.GetString("CongTy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH MỤC.
        /// </summary>
        internal static string DanhMuc {
            get {
                return ResourceManager.GetString("DanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐẶT PHÒNG.
        /// </summary>
        internal static string DatPhong {
            get {
                return ResourceManager.GetString("DatPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đia chỉ.
        /// </summary>
        internal static string DiaChi {
            get {
                return ResourceManager.GetString("DiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string DienThoai {
            get {
                return ResourceManager.GetString("DienThoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string GioiThieu {
            get {
                return ResourceManager.GetString("GioiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giường phụ.
        /// </summary>
        internal static string GiuongPhu {
            get {
                return ResourceManager.GetString("GiuongPhu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đi.
        /// </summary>
        internal static string GuiDi {
            get {
                return ResourceManager.GetString("GuiDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string HoTen {
            get {
                return ResourceManager.GetString("HoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        internal static string LienHe {
            get {
                return ResourceManager.GetString("LienHe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phòng.
        /// </summary>
        internal static string LoaiPhong {
            get {
                return ResourceManager.GetString("LoaiPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đến.
        /// </summary>
        internal static string NgayDen {
            get {
                return ResourceManager.GetString("NgayDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đi.
        /// </summary>
        internal static string NgayDi {
            get {
                return ResourceManager.GetString("NgayDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người lớn.
        /// </summary>
        internal static string NguoiLon {
            get {
                return ResourceManager.GetString("NguoiLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại.
        /// </summary>
        internal static string NhapLai {
            get {
                return ResourceManager.GetString("NhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        internal static string QuocGia {
            get {
                return ResourceManager.GetString("QuocGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đêm.
        /// </summary>
        internal static string SoDem {
            get {
                return ResourceManager.GetString("SoDem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng khách.
        /// </summary>
        internal static string SoLuongKhach {
            get {
                return ResourceManager.GetString("SoLuongKhach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách vui lòng điền đủ các thông tin được yêu cầu dưới đây để đặt phòng tại khách sạn Ha LongParadise..
        /// </summary>
        internal static string ThongBao {
            get {
                return ResourceManager.GetString("ThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string ThongTin {
            get {
                return ResourceManager.GetString("ThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin khách hàng.
        /// </summary>
        internal static string ThongTinKhachHang {
            get {
                return ResourceManager.GetString("ThongTinKhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trẻ nhỏ.
        /// </summary>
        internal static string TreNho {
            get {
                return ResourceManager.GetString("TreNho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các Yêu cầu khác.
        /// </summary>
        internal static string YeuCauKhac {
            get {
                return ResourceManager.GetString("YeuCauKhac", resourceCulture);
            }
        }
    }
}
